version: '3.9'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file: .env
    command: >
      sh -c "python automarket/manage.py wait_for_db &&
             python automarket/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A automarket worker --loglevel=info --pool=solo
    volumes:
      - ./backend/automarket:/app
    depends_on:
      - db
      - redis
    env_file: .env


volumes:
  postgres_data:
