FROM python:3.12-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       libpq-dev gcc build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

CMD ["python", "automarket/manage.py", "runserver", "0.0.0.0:8000"]
