# Generated by Django 5.0 on 2024-08-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0002_favorite_favorite_unique_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
