# Generated by Django 5.0 on 2024-08-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0003_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
