# Generated by Django 5.0 on 2024-08-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0004_carlisting_is_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='country',
            new_name='origin_country',
        ),
    ]
